global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ml-inference-api"
    static_configs:
      - targets: ["ml-api:8001"]
    metrics_path: "/metrics"
    scheme: http

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
